# Generated by Django 5.2.6 on 2025-09-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.IntegerField(choices=[(1, 'Buy'), (-1, 'Sell')], default=1)),
                ('status', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Partially Filled'), (3, 'Filled'), (4, 'Canceled')], default=1)),
                ('avg_order_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('avg_trade_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('traded_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('order_alive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avg_trade_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='order.order')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
