# Generated by Django 5.2.6 on 2025-09-26 15:32

import django.utils.timezone
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_avg_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('order_id', models.BigIntegerField()),
                ('version', models.PositiveIntegerField(choices=[(1, 'Order Created'), (2, 'Order Updated'), (3, 'Order Deleted')])),
                ('payload_text', models.TextField(validators=[order.models.validate_json_string])),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['published_at', 'created_at'], name='order_outbo_publish_aa0ced_idx'), models.Index(fields=['order_id', 'version'], name='order_outbo_order_i_257932_idx')],
            },
        ),
    ]
