# Generated by Django 5.2.6 on 2025-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_version_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default='default_trade_id', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
